# Generated by Django 4.2 on 2023-04-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("create_data", models.DateTimeField()),
                ("email", models.CharField(max_length=240, unique=True)),
                ("phone", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("create_data", models.DateTimeField()),
                ("email", models.CharField(max_length=240, unique=True)),
                ("gdpr_consent", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="SubscriberSMS",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("create_data", models.DateTimeField()),
                ("phone", models.CharField(max_length=20, unique=True)),
                ("gdpr_consent", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="AppUser",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("create_data", models.DateTimeField()),
                ("email", models.CharField(max_length=240)),
                ("phone", models.CharField(max_length=20)),
                ("gdpr_consent", models.BooleanField()),
            ],
        ),
    ]
