# Generated by Django 4.2 on 2023-04-05 11:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appuser",
            old_name="create_data",
            new_name="create_date",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="create_data",
            new_name="create_date",
        ),
        migrations.RenameField(
            model_name="subscriber",
            old_name="create_data",
            new_name="create_date",
        ),
        migrations.RenameField(
            model_name="subscribersms",
            old_name="create_data",
            new_name="create_date",
        ),
    ]
